services:
  - type: web
    name: originone-chatbot
    env: node
    plan: free
    buildCommand: npm install
    startCommand: node src/index.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: META_VERIFY_TOKEN
        value: originone_secure_token_2026
      - key: ADMIN_WHATSAPP_NUMBERS
        value: 528110653947,528120989813
